blank_issues_enabled: false
contact_links:
  - name: Une faille de sécurité ?
    url: https://github.com/Louis-htmlcss/test-du-workflows/security/advisories/new
    about: Merci de nous contacter via ce formulaire

  - name: Une question ? Un problème personnel ?
    url: https://discord.gg/WXntBawAk8
    about: L'équipe Papillon est disponible sur Discord, nous pouvons répondre aux questions
