name: QR Code (by godetremy)
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preview:
    name: Preview with ExpoGo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Create dist folder
        run: |
          mkdir dist
          mkdir dist/expo

      - name: Export AppEntry
        run: |
          npx expo export --dev --platform ios --output-dir build_ios
          npx expo export --dev --platform android --output-dir build_android

      - name: Move iOS AppEntry
        run: |
          cd build_ios
          PATH_TO_ENTRY="$(find . | grep 'AppEntry.js')"
          mv $PATH_TO_ENTRY ./../dist/expo/AppEntry_ios.js
          cd ..

      - name: Move Android AppEntry
        run: |
          cd build_android
          PATH_TO_ENTRY="$(find . | grep 'AppEntry.js')"
          mv $PATH_TO_ENTRY ./../dist/expo/AppEntry_android.js
          cd ..

      - name: Move assets
        run: |
          mv build_ios/assets dist/assets

      - name: Copy app.json
        run: cp app.json dist/app.json

      - name: Cleanup
        run: rm -rf build_ios build_android

      - name: Cloning the server repository
        run: |
          git clone https://github.com/Kgeek33/Expo-server-Github-Repo.git server_repo

      - name: Moving the build to the server repository
        run: |
          mkdir -p server_repo/builds/${{ github.event.pull_request.number }}
          cp -r dist/* server_repo/builds/${{ github.event.pull_request.number }}
          cd server_repo
          git config user.email "noreply@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Add build for PR #${{ github.event.pull_request.number }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/godetremy/Expo-server-Github-Repo.git
          cd ..

      - name: Commenting on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              <h1 align="center">🎉 La preview est prête 🎉</h1>

              #### iOS QR Code
              ![iOS QR Code](http://api.qrserver.com/v1/create-qr-code/?data=http://expo-server.com/builds/${{ github.event.pull_request.number }}/ios&size=150x150&margin=5)

              #### Android QR Code
              ![Android QR Code](http://api.qrserver.com/v1/create-qr-code/?data=http://expo-server.com/builds/${{ github.event.pull_request.number }}/android&size=150x150&margin=5)
              `
            });
