name: PR QR Code Setup
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup-qr-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: qr-code-workflows
          fetch-depth: 0
      
      - name: Generate unique PR identifier
        run: echo "PR_ID=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      
      - name: Create QR code workflow
        run: |
          mkdir -p .github/workflows
          sed "s/\${PR_NUMBER}/${{ github.event.pull_request.number }}/g" workflows-secondaires.txt > .github/workflows/qr-code-${{ env.PR_ID }}.yml
      
      - name: Commit and push new workflow
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/workflows/qr-code-${{ env.PR_ID }}.yml
          git commit -m "Add QR code workflow for ${{ env.PR_ID }}"
          git push origin qr-code-workflows
      
      - name: Trigger new workflow
        run: |
          gh workflow run qr-code-${{ env.PR_ID }}.yml --ref qr-code-workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}