name: Create QR Code Workflow for PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    permissions: write-all
    uses: ./.github/workflows/test1.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}