name: PR QR Code Generator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup_qr_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Checkout qr-code-workflows branch
        uses: actions/checkout@v3
        with:
          ref: qr-code-workflows
          path: qr-code-workflows

      - name: Generate unique ID for PR
        run: echo "PR_ID=$(echo ${{ github.event.pull_request.number }}-$(date +%s))" >> $GITHUB_ENV

      - name: Read QR workflow template
        id: template
        run: |
          TEMPLATE=$(cat qr-code-workflows/qr-workflow-template.txt)
          echo "TEMPLATE<<EOF" >> $GITHUB_OUTPUT
          echo "$TEMPLATE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create QR workflow file
        run: |
          WORKFLOW_CONTENT=$(echo '${{ steps.template.outputs.TEMPLATE }}' | \
            sed 's/{PR_NUMBER}/${{ github.event.pull_request.number }}/g' | \
            sed 's/{UNIQUE_ID}/${{ env.PR_ID }}/g' | \
            sed 's/{PR_BRANCH}/${{ github.event.pull_request.head.ref }}/g')
          echo "$WORKFLOW_CONTENT" > qr-code-workflows/qr-workflow-pr-${{ github.event.pull_request.number }}-${{ env.PR_ID }}.yml

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit and push QR workflow file
        working-directory: qr-code-workflows
        run: |
          git add qr-workflow-pr-${{ github.event.pull_request.number }}-${{ env.PR_ID }}.yml
          git commit -m "Add QR workflow for PR #${{ github.event.pull_request.number }}"
          git push origin qr-code-workflows

      - name: Trigger QR workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: `qr-workflow-pr-${{ github.event.pull_request.number }}-${{ env.PR_ID }}.yml`,
              ref: 'qr-code-workflows'
            });

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'QR code generation for this PR has been initiated. The QR code will be posted in a separate comment once it\'s ready.'
            })

  cleanup_old_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout qr-code-workflows branch
        uses: actions/checkout@v3
        with:
          ref: qr-code-workflows

      - name: Remove old workflow files
        run: |
          for file in qr-workflow-pr-${{ github.event.pull_request.number }}-*.yml; do
            if [ -f "$file" ]; then
              git rm "$file"
            fi
          done

      - name: Commit and push changes
        run: |
          if [[ -n $(git status -s) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Remove old QR workflows for PR #${{ github.event.pull_request.number }}"
            git push origin qr-code-workflows
          fi