name: PR QR Code Generator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup_qr_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate unique ID for PR
        run: echo "PR_ID=$(echo ${{ github.event.pull_request.number }}-$(date +%s))" >> $GITHUB_ENV
      - name: Create QR workflow file
        run: |
          cat << EOF > qr-workflow-${{ env.PR_ID }}.yml
          name: QR Code Generator for PR #${{ github.event.pull_request.number }}
          
          on:
            workflow_dispatch:
          
          jobs:
            generate_qr:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v3
                  with:
                    ref: ${{ github.event.pull_request.head.ref }}
                - name: Setup Node.js
                  uses: actions/setup-node@v3
                  with:
                    node-version: '18'
                - name: Install dependencies
                  run: npm ci
                - name: Start Expo server
                  run: npx expo start > expo.log &
                - name: Extract QR code
                  run: |
                    while ! grep -q "Metro waiting on" expo.log; do sleep 1; done
                    QR_CODE=$(sed -n '/QR code:/,/Press/p' expo.log)
                    echo "$QR_CODE" > qr_code.txt
                - name: Update PR comment
                  uses: actions/github-script@v6
                  with:
                    github-token: \${{ secrets.GITHUB_TOKEN }}
                    script: |
                      const fs = require('fs');
                      const qrCode = fs.readFileSync('qr_code.txt', 'utf8');
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: \`QR Code for this PR:\n\`\`\`\n\${qrCode}\n\`\`\`\`
                      });
                # Add steps for creating next workflow file and cleanup
          EOF
      - name: Commit and push QR workflow file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b qr-code-workflows
          git add qr-workflow-${{ env.PR_ID }}.yml
          git commit -m "Add QR workflow for PR #${{ github.event.pull_request.number }}"
          git push origin qr-code-workflows
      - name: Trigger QR workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'qr-workflow-${{ env.PR_ID }}.yml',
              ref: 'qr-code-workflows'
            });