name: Fetch File from Another Branch and Push Changes

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fetch-file-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: qr-code-workflows
      - name: Display file content
        run: cat qr-workflow-template.txt
      
      - name: Copy and rename file to directory
        run: |
          mkdir -p qr-code-workflows
          cp qr-workflow-template.txt qr-code-workflows/qr-workflow-template.yml
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add qr-workflow-template.yml"

      