name: Fetch File from Another Branch

on:
  workflow_dispatch:

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch file from another branch
        run: |
          git fetch origin qrcode-code-workflows:qrcode-code-workflows
          git checkout qrcode-code-workflows -- file.txt
        
      - name: Display file content
        run: cat path/to/your/file.txt

      # Ajoutez ici d'autres étapes pour utiliser le fichier récupéré