name: Create QR Code Workflow for PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-qr-workflow:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  build:
    permissions: write-all
    uses: ./.github/workflows/test1.yml@main