name: Fetch File from Another Branch

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch file from another branch
        run: |
          git fetch origin qr-code-workflows:qr-code-workflows
          git checkout qr-code-workflows -- qr-workflow-template.txt
        
      - name: Create PR directory and copy file
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          mkdir -p "PR_$PR_NUMBER"
          cp qr-workflow-template.txt "PR_$PR_NUMBER/qr-workflow-template.yml"
        
      - name: Display file content
        if: github.event_name == 'pull_request'
        run: cat "PR_${{ github.event.pull_request.number }}/qr-workflow-template.yml"
      
      
      - name: Commit and push changes
        if: github.event_name == 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b pr-${{ github.event.pull_request.number }}-qr-workflow
          git add "PR_${{ github.event.pull_request.number }}/qr-workflow-template.yml"
          git commit -m "Add qr-workflow-template.yml for PR #${{ github.event.pull_request.number }}"
          git push origin pr-${{ github.event.pull_request.number }}-qr-workflow

      - name: Delete PR directory
        if: github.event_name == 'pull_request'
        run: |
          rm -rf "PR_${{ github.event.pull_request.number }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Remove PR_${{ github.event.pull_request.number }} directory"
          git push