name: Fetch File from Another Branch and Push Changes

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fetch-file-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Permission to push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Copy and rename file to .github/workflows directory
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          cp qr-workflow-template.txt ".github/workflows/qr-workflow-$PR_NUMBER.yml"
      
      - name: Commit and push the new workflow file
        run: |
          git add .github/workflows/qr-workflow-$PR_NUMBER.yml
          git commit -m "Add qr-workflow-$PR_NUMBER.yml for PR #$PR_NUMBER"
          git push origin qr-code-workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Trigger the new workflow
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          WORKFLOW_FILE=".github/workflows/qr-workflow-$PR_NUMBER.yml"
          gh workflow run $WORKFLOW_FILE --ref qr-code-workflows
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}